title: Matias Energy-store # your site title
author: Matias
email: deka5224@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://san-matias.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  san-matias # replace with your_github_username or comment to remove link from footer
instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
social:
  name: Matias
  links:
    - https://www.facebook.com/ben.balter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

disqus:
  shortname: Matias # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
remote_theme: jekyll-sleek
highlighter: rouge # or pygments or null
theme: jekyll-theme-cayman
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
